<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soccer" nsURI="platform:/plugin/no.ntnu.soccer.model/model/soccer.ecore"
    nsPrefix="soccer">
  <eClassifiers xsi:type="ecore:EClass" name="Federation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" upperBound="-1"
        eType="#//Country" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="league" eType="#//League"
        containment="true" eOpposite="#//League/country"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="League">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="1"
        eType="#//Country" eOpposite="#//Country/league"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seasons" upperBound="-1"
        eType="#//Season" containment="true" eOpposite="#//Season/league"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="-1"
        eType="#//Team" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Season">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="league" lowerBound="1"
        eType="#//League" eOpposite="#//League/seasons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchDays" upperBound="-1"
        eType="#//MatchDay" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="standing" lowerBound="1"
        eType="#//Standing" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchDay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placements" lowerBound="1"
        eType="#//Placement" eOpposite="#//Placement/team"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Placement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wins" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="draws" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="losses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalsFor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalsAgainst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalDifference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team" upperBound="-1" eType="#//Team"
        eOpposite="#//Team/placements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="standing" lowerBound="1"
        eType="#//Standing" eOpposite="#//Standing/placements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="season" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Standing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="placements" upperBound="-1"
        eType="#//Placement" containment="true" eOpposite="#//Placement/standing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeTeamGoal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="awayTeamGoal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="#//MatchResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opponents" lowerBound="2"
        upperBound="2" eType="#//Opponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MatchResult">
    <eLiterals name="DRAW"/>
    <eLiterals name="HOME_WIN" value="1"/>
    <eLiterals name="AWAY_WIN" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TeamType">
    <eLiterals name="HOME_TEAM"/>
    <eLiterals name="AWAY_TEAM" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Opponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TeamType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineup" upperBound="4"
        eType="#//Position" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team" lowerBound="1" eType="#//Team"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PositionType">
    <eLiterals name="KEEPER"/>
    <eLiterals name="DEFENCE" value="1"/>
    <eLiterals name="MIDFIELD" value="2"/>
    <eLiterals name="FORWARD" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PositionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="11"
        eType="#//Player"/>
  </eClassifiers>
</ecore:EPackage>
